hw1 added
made-mlops-2022/roman_zilotov pull request #1
Opened 2022-11-10 20:58 UTC by ziphyrr

2022-11-11 03:47 UTC, ziphyrr commented
### Комментарий с самооценкой:

1. В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание того, что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код **1/1**
2. В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) **1/1**
3. Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы). Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл)  **1/2**
4. Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла) **3/3**
5. Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла) **3/3**
6. Проект имеет модульную структуру (2 балла) **2/2**
7. Использованы логгеры (2 балла) **2/2**
8. Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла). Для тестов генерируются синтетические данные, приближенные к реальным (2 балла) **5/5**
9. Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) **3/3**
10. Используются датаклассы для сущностей из конфига, а не голые dict (2 балла) **2/2**
11. Напишите кастомный трансформер и протестируйте его (3 балла) **3/3**
12. В проекте зафиксированы все зависимости (1 балл) **1/1**
13. Настроен CI для прогона тестов, линтера на основе github actions (3 балла) **3/3**

Итого: **30 баллов**
С учетом невыполненного софт-дедлайна: **18 баллов**

2022-11-19 19:37 UTC, ziphyrr commented
Прошу прощения, что так поздно добавляю вас в assignees и reviewers, забыл это сделать изначально

2022-11-25 14:24 UTC, SVizor42 commented on hw1_project/src/train_pipeline.py
> +    y = data['condition']
Не нужно хардкодить таргет, берем из конфига

2022-11-25 14:24 UTC, SVizor42 commented on hw1_project/src/data/data_loader.py
> +    #print(os.environ.keys())
Закомментированные участки кода лучше не коммитить

2022-11-25 14:26 UTC, SVizor42 commented on hw1_project/src/train_pipeline.py
> +from hydra.core.config_store import ConfigStore
Стандартные модули идут перед локальными импортами

2022-11-25 14:28 UTC, SVizor42 commented on hw1_project/src/train_pipeline.py
> +    data_transformed = pd.concat([X_train_transformed, pd.DataFrame(y_train, columns=['condition'])], axis=1)
Опять таргет

2022-11-25 14:29 UTC, SVizor42 commented on hw1_project/src/train_pipeline.py
> +    data = pd.read_csv(PATH_TO_SRC.joinpath('data/raw/heart_cleveland_upload.csv'))
Все пути к данным, моделям и артефактам лучше прописывать также в конфиге

2022-11-25 14:30 UTC, SVizor42 commented on hw1_project/src/models/model_train.py
> +DEFAULT_TRAIN_SIZE_FOR_GRID_SEARCH = 0.8
Так тоже ок. Но можно отправить и в конфиг :)

2022-11-25 14:32 UTC, SVizor42 commented on hw1_project/src/models/model_train.py
> +        ps = PredefinedSplit(split_rule)
Таких малоинформативных идентификаторов лучше избегать

2022-11-25 14:35 UTC, SVizor42 commented on hw1_project/tests/make_synthetic_data.py
> +from src import PATH_TO_SRC
Локальный импорты после стандартных

2022-11-25 14:51 UTC, SVizor42 requested changes
Необходимо:
1. Исключить ненужные папки из ветки (файлы IDE, кэшей, запусков и т.д.).
2. Прогнать код через линтер.
3. Посмотреть комментарии.

2022-12-05 21:47 UTC, ziphyrr commented
### Комментарий с самооценкой(upd):

1. В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание того, что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код **1/1**
2. В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) **1/1**
3. Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы). Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл)  **1/2**
4. Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла) **3/3**
5. Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла) **3/3**
6. Проект имеет модульную структуру (2 балла) **2/2**
7. Использованы логгеры (2 балла) **2/2**
8. Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла). Для тестов генерируются синтетические данные, приближенные к реальным (2 балла) **5/5**
9. Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) **3/3**
10. Используются датаклассы для сущностей из конфига, а не голые dict (2 балла) **2/2**
11. Напишите кастомный трансформер и протестируйте его (3 балла) **3/3**
12. В проекте зафиксированы все зависимости (1 балл) **1/1**
13. Настроен CI для прогона тестов, линтера на основе github actions (3 балла) **3/3**

Дополнительные баллы:
- Используйте hydra для конфигурирования  **(3 / 3)**
Mlflow:
- разверните локально mlflow или на какой-нибудь виртуалке **(0 / 1)**
- залогируйте метрики **(0 / 1)**
- воспользуйтесь Model Registry для регистрации модели **(0 / 1)**
- выделите в своем проекте несколько entrypoints в виде консольных утилит **(1 / 1)**
- добавьте датасет под контроль версий **(0 / 1)**
- сделайте dvc пайплайн(связывающий запуск нескольких entrypoints) для изготовления модели **(0 / 1)**


Итого: **34 балла**
С учетом невыполненного софт-дедлайна: **20 баллов**

2022-12-06 12:14 UTC, SVizor42 approved these changes
**Сумма: 20.4 балла**

Ветку можно мерджить.

2022-12-06 12:23 UTC, merged